spring:
  security:
    user:
      password: 1234

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2/base
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: classpath:additional.yml